// Package attach hosts the in-pane vt terminal emulator that powers
// embedded attach mode. A VTTerm wraps github.com/charmbracelet/x/vt so a
// child PTY's screen renders inside the TUI content pane while sidebar +
// status remain visible.
package attach

import (
	"context"
	"errors"
	"io"
	"sync"
	"sync/atomic"

	uv "github.com/charmbracelet/ultraviolet"
	"github.com/charmbracelet/x/ansi"
	"github.com/charmbracelet/x/vt"
)

// closer is the interface a writable pipe satisfies. Used to unblock the
// drain goroutine without racing on the emulator's internal `closed` bool.
type closer interface{ Close() error }

// VTTerm wraps a vt.Emulator with a session lifecycle and a coalesced
// screen-changed notifier. Construction starts the reply-drain goroutine
// that forwards CPR / DA / SendKey output to the supplied PTY writer.
//
// IMPORTANT: x/vt's Emulator.Write blocks if Read is not concurrently
// drained — the drain goroutine MUST be running before any Write is
// called on the emulator. NewVTTerm guarantees this.
type VTTerm struct {
	mu sync.Mutex
	em *vt.Emulator

	// ptyOut receives bytes the emulator generates (replies + sent keys).
	// Typically wired to the PTY master ƒile.
	ptyOut io.Writer

	cancel    context.CancelFunc
	drainDone chan struct{}

	// notify is a coalescing channel — at most one pending screen-changed
	// ping. Drained by the TUI refresh loop.
	notify chan struct{}

	// mouseMask is a bitmask of the child's currently-active mouse tracking
	// modes (see mouseModeBit). Written only from the EnableMode/DisableMode
	// callbacks, which fire synchronously inside em.Write while t.mu is held —
	// so they MUST NOT relock t.mu. An atomic lets the TUI goroutine read
	// MouseTracking() without that lock.
	mouseMask atomic.Uint32

	closed atomic.Bool
}

// mouseModeBit maps a DEC private mouse-tracking mode to a bit in
// VTTerm.mouseMask. Returns 0 for any non-mouse mode.
func mouseModeBit(mode ansi.Mode) uint32 {
	switch mode {
	case ansi.X10MouseMode:
		return 1 << 0
	case ansi.NormalMouseMode:
		return 1 << 1
	case ansi.HighlightMouseMode:
		return 1 << 2
	case ansi.ButtonEventMouseMode:
		return 1 << 3
	case ansi.AnyEventMouseMode:
		return 1 << 4
	}
	return 0
}

// NewVTTerm constructs a VTTerm with the given dimensions in cells. ptyOut
// is the destination for bytes the emulator generates (CPR replies,
// SendKey output). Pass an io.Discard if no PTY is attached.
func NewVTTerm(cols, rows int, ptyOut io.Writer) *VTTerm {
	if cols <= 0 {
		cols = 80
	}
	if rows <= 0 {
		rows = 24
	}
	em := vt.NewEmulator(cols, rows)

	ctx, cancel := context.WithCancel(context.Background())
	t := &VTTerm{
		em:        em,
		ptyOut:    ptyOut,
		cancel:    cancel,
		drainDone: make(chan struct{}),
		notify:    make(chan struct{}, 1),
	}

	// Track the child's mouse-tracking modes so the TUI can decide whether to
	// forward mouse events to the child or run a local drag-select. These
	// callbacks fire inside em.Write (under t.mu) — keep them lock-free.
	em.SetCallbacks(vt.Callbacks{
		EnableMode: func(mode ansi.Mode) {
			if b := mouseModeBit(mode); b != 0 {
				t.mouseMask.Or(b)
			}
		},
		DisableMode: func(mode ansi.Mode) {
			if b := mouseModeBit(mode); b != 0 {
				t.mouseMask.And(^b)
			}
		},
	})

	go t.drain(ctx)
	return t
}

// MouseTracking reports whether the child currently has any mouse-tracking
// mode enabled (X10/Normal/Highlight/ButtonEvent/AnyEvent). When true the TUI
// forwards mouse events to the child; when false it runs a local drag-select.
func (t *VTTerm) MouseTracking() bool { return t.mouseMask.Load() != 0 }

// drain copies emulator-generated bytes (replies, key encodings) to the
// PTY writer. Exits on Close().
func (t *VTTerm) drain(ctx context.Context) {
	defer close(t.drainDone)
	buf := make([]byte, 4096)
	for {
		// Read blocks until bytes available or emulator closed.
		n, err := t.em.Read(buf)
		if n > 0 && t.ptyOut != nil {
			_, werr := t.ptyOut.Write(buf[:n])
			if werr != nil {
				// PTY closed — emulator stays alive; caller will
				// detect via auto-detach on its own write attempt.
			}
		}
		if err != nil {
			return
		}
		// Allow Close to interrupt: if ctx done, bail.
		if ctx.Err() != nil {
			return
		}
	}
}

// Write feeds PTY output bytes into the emulator. Pings the notifier so
// the TUI re-renders. Implements io.Writer so it can be passed to
// process.Manager.Subscribe.
func (t *VTTerm) Write(p []byte) (int, error) {
	if t.closed.Load() {
		return 0, errors.New("vtterm closed")
	}
	t.mu.Lock()
	n, err := t.em.Write(p)
	t.mu.Unlock()
	t.ping()
	return n, err
}

// SendKey queues a key event; emulator encodes correctly per DECCKM /
// keypad mode and the encoded bytes flow out through ptyOut via the drain
// pump.
func (t *VTTerm) SendKey(k uv.KeyEvent) {
	if t.closed.Load() {
		return
	}
	t.mu.Lock()
	t.em.SendKey(k)
	t.mu.Unlock()
}

// SendMouse queues a mouse event; emulator encodes per active mouse mode.
func (t *VTTerm) SendMouse(m uv.MouseEvent) {
	if t.closed.Load() {
		return
	}
	t.mu.Lock()
	t.em.SendMouse(m)
	t.mu.Unlock()
}

// Paste sends text bracketed if mode 2004 active, raw otherwise.
func (t *VTTerm) Paste(text string) {
	if t.closed.Load() {
		return
	}
	t.mu.Lock()
	t.em.Paste(text)
	t.mu.Unlock()
}

// Resize changes the emulator grid dimensions in cells.
func (t *VTTerm) Resize(cols, rows int) {
	if t.closed.Load() {
		return
	}
	t.mu.Lock()
	t.em.Resize(cols, rows)
	t.mu.Unlock()
	t.ping()
}

// CellAt returns the cell at (x, y) or nil if out of bounds.
func (t *VTTerm) CellAt(x, y int) *uv.Cell {
	t.mu.Lock()
	defer t.mu.Unlock()
	return t.em.CellAt(x, y)
}

// Width returns the current grid width in cells.
func (t *VTTerm) Width() int {
	t.mu.Lock()
	defer t.mu.Unlock()
	return t.em.Width()
}

// Height returns the current grid height in cells.
func (t *VTTerm) Height() int {
	t.mu.Lock()
	defer t.mu.Unlock()
	return t.em.Height()
}

// CursorPosition returns the cursor (x, y) in the active screen.
func (t *VTTerm) CursorPosition() uv.Position {
	t.mu.Lock()
	defer t.mu.Unlock()
	return t.em.CursorPosition()
}

// IsAltScreen reports whether the alt buffer is active (vim, less, top).
func (t *VTTerm) IsAltScreen() bool {
	t.mu.Lock()
	defer t.mu.Unlock()
	return t.em.IsAltScreen()
}

// Notify returns a channel that pings whenever the screen may have
// changed. Coalesced — never blocks producers, never floods consumers.
func (t *VTTerm) Notify() <-chan struct{} {
	return t.notify
}

func (t *VTTerm) ping() {
	select {
	case t.notify <- struct{}{}:
	default:
	}
}

// Close shuts down the drain goroutine and releases resources.
//
// The library has an unsynchronised race on Emulator.closed between Read
// and Close. To dodge it we close the input pipe directly (which unblocks
// Read with io.EOF) rather than calling em.Close while drain is reading.
// The emulator object is then effectively dead; we drop our reference.
func (t *VTTerm) Close() error {
	if !t.closed.CompareAndSwap(false, true) {
		return nil
	}
	t.cancel()
	// InputPipe returns *io.PipeWriter; closing it closes the read side
	// with io.EOF on the very next Read, unblocking drain without writing
	// to em.closed.
	if pw, ok := t.em.InputPipe().(closer); ok {
		_ = pw.Close()
	}
	<-t.drainDone
	return nil
}
